spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/authserver?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
logging:
  level:
    org:
      springframework:
        security: TRACE
server:
  port: 8082

asp:
  auth:
    provider-uri: "http://localhost:8082"
    jks:
      keypass: 123456
      storepass: 123456
      alias: awblog
      path: keystore/asp.jks